# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(b'TYPE_CUSTOMER', b'Customer'), (b'TYPE_AGENT', b'Agent')], default=b'CU', max_length=2),
        ),
    ]
