# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160427_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcm_token',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
