# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160504_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gcm_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
