# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gcm_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
