# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('order_type', models.CharField(choices=[(b'PU', b'Purchase'), (b'DL', b'Delivery')], max_length=2)),
                ('estimate', models.IntegerField(blank=True, null=True)),
                ('destination_lat', models.CharField(max_length=6)),
                ('destination_long', models.CharField(max_length=6)),
                ('source_lat', models.CharField(blank=True, max_length=6)),
                ('source_long', models.CharField(blank=True, max_length=6)),
                ('status', models.CharField(choices=[(b'PN', b'Pending'), (b'AC', b'Accepted'), (b'PK', b'Picked'), (b'PR', b'Purchased'), (b'DV', b'Delivery'), (b'CM', b'Completed'), (b'CN', b'Cancelled')], default=b'PN', max_length=2)),
                ('cost_delivery', models.IntegerField(blank=True, null=True)),
                ('cost_purchase', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
