# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_desc',
            field=models.TextField(default='Tower 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='source_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_lat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_long',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_lat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_long',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
