# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160427_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_lat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_long',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_lat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_long',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
